name: 'Create Cluster'
description: 'Create Cluster'
inputs:
  api-token:
    description: 'API Token.'
    required: true
    default: ''
  kubernetes-distribution:
    description: 'Kubernetes distribution of the cluster to provision.'
    required: true
  kubernetes-version:
    description: 'Kubernetes version to provision (format is distribution dependent).'
    required: true
  cluster-name:
    description: 'Name of the cluster to provision'
    required: true
    default: ''
  ttl:
    description: 'Cluster TTL (duration) (default "2h")'
    required: true
    default: '2h'
outputs:
  cluster-id: # id of the cluster
    description: 'Contains the cluster id.'
  cluster-kubeconfig: # kubeconfig of the cluster
    description: 'Contains the kubeconfig to connect with the cluster.'
runs:
  using: 'node16'
  main: 'dist/index.js'