name: 'Replicated create release'
description: 'Create a Replicated release on a channel'
inputs:
  app-slug:
    description: 'App Slug.'
    required: true
    default: ''
  api-token:
    description: 'API Token.'
    required: true
    default: ''
  yaml-dir:
    description: 'The directory containing multiple yamls for a Replicated release.'
    required: false
    default: 'manifests'
  chart:
    description: 'The Helm chart tarball for a Replicated release'
    required: false
    default: ''
  promote-channel:
    description: 'Channel name or id to promote this release to.'
    required: false
    default: ''
  version:
    description: 'Release version'
    required: false
    default: '${GITHUB_SHA::7}'
outputs:
  channel-slug: # slug of the channel
    description: 'Contains the channel slug.'
  release-sequence: # sequence number of the release
    description: 'Sequence number of the release.'
runs:
  using: 'node16'
  main: 'dist/index.js'
