name: 'Smoke Test'
description: 'Smoke Test'
inputs:
  app-slug:
    description: 'App Slug.'
    required: true
    default: ''
  api-token:
    description: 'API Token.'
    required: true
    default: ''
  yaml-dir:
    description: 'The directory containing multiple yamls for a Replicated release.'
    required: true
    default: 'manifests'
  kubernetes-distribution:
    description: 'Kubernetes distribution of the cluster to provision.'
    required: true
  kubernetes-version:
    description: 'Kubernetes version to provision (format is distribution dependent).'
    required: true
  installation-method:
    description: "Method to install the application [helm|kots] (default: helm)"
    required: true
    default: "helm"
  helm-values:
    description: 'A Helm values.yaml file to use'
    required: false
  helm-chart-name:
    description: 'The name of the Helm chart to use'
    required: false
  kots-config-values:
    description: 'The KOTS config values to use'
    required: false
  test-script:
    description: "Location of the test script to run (default: test.sh)"
    required: true
    default: "test.sh"
runs:
  using: "composite"
  steps:
  - name: Extract Chart YAML
    id: extract-chart-yaml
    shell: bash
    run: |
      tarball=$(find ${YAML_DIR} -name "${CHART_NAME}*.tgz")
      chart_yaml=$(tar -xzvf ${tarball} $(tar -tzf ${tarball} --exclude "*/charts/*" | grep Chart.yaml))
      echo "CHART_YAML=${chart_yaml}" >> $GITHUB_ENV
    env:
      YAML_DIR: ${{ inputs.yaml-dir }}
      CHART_NAME: ${{ inputs.helm-chart-name }}
  - name: Get Chart Version
    id: get-chart-version
    uses: mikefarah/yq@master
    with:
      cmd: yq '.version' ${CHART_YAML}
  - name: Define App Version
    shell: bash
    run: echo "APP_VERSION=${CHART_VERSION}-${GITHUB_REF_NAME//[^a-zA-Z0-9]/}.${GITHUB_RUN_ID}${GITHUB_RUN_ATTEMPT}" >> $GITHUB_ENV
    env:
      CHART_VERSION: ${{ steps.get-chart-version.outputs.result }}
  - name: Define Channel Name
    shell: bash
    run: echo "CHANNEL_NAME=${{ github.ref_name }}-${GITHUB_RUN_ID}${GITHUB_RUN_ATTEMPT}-${{ inputs.kubernetes-distribution }}-${{ inputs.kubernetes-version }}" >> $GITHUB_ENV
  - name: Update Chart YAML
    id: update-chart-yaml
    uses: mikefarah/yq@master
    with:
      cmd: yq  -i '.version = "${{ env.APP_VERSION }}"' ${CHART_YAML}
  - name: Update Chart Version
    id: update-chart-version
    shell: bash
    if: ${{ inputs.installation-method == 'helm' }}
    run: |
      # update the chart version to match the Replicated app version
      tarball=$(find ${YAML_DIR} -name "${CHART_NAME}*.tgz")
      tar -xvf ${tarball%tgz} -C /tmp/repack
      helm package --version "${{ env.APP_VERSION }}" /tmp/repack
      mv /tmp/repack/${{ inputs.helm-chart-name }}-${{env.APP_VERSION }}.tgz $(dirname ${tarball })
      rm ${tarball}
    env:
      YAML_DIR: ${{ inputs.yaml-dir }}
  - name: 'Create Release'
    id: 'create-release'
    uses: replicatedhq/compatibility-actions/create-release@v0
    with:
      app-slug: ${{ inputs.app-slug }}
      api-token: ${{ inputs.api-token }}
      yaml-dir: ${{ inputs.yaml-dir }}
      promote-channel: ${{ env.CHANNEL_NAME }}
      version: ${{ env.APP_VERSION }}
  - name: 'Create Customer'
    id: 'create-customer'
    uses: replicatedhq/compatibility-actions/create-customer@v0
    with:
      app-slug: ${{ inputs.app-slug }}
      api-token: ${{ inputs.api-token }}
      customer-name: ${{ github.ref_name }}-${{ inputs.kubernetes-distribution }}-${{ inputs.kubernetes-version }}
      customer-email: ${{ github.ref_name }}@example.com
      license-type: "dev"
      channel-slug: ${{ steps.create-release.outputs.channel-slug }}
      expires-in: 14
  - name: Create Cluster
    id: create-cluster
    uses: replicatedhq/compatibility-actions/create-cluster@v0
    with:
      api-token: ${{ inputs.api-token }}
      kubernetes-distribution: ${{ inputs.kubernetes-distribution }}
      kubernetes-version: ${{ inputs.kubernetes-version }}
      cluster-name: ${{ github.ref_name }}-${{ inputs.kubernetes-distribution }}-${{ inputs.kubernetes-version }}
      ttl: 10m
  - name: Deploy the app with Helm
    uses: replicatedhq/compatibility-actions/helm-install@v0
    if: ${{ inputs.installation-method == 'helm' }}
    with:
      kubeconfig: ${{ steps.create-cluster.outputs.cluster-kubeconfig }}
      helm-path: "helm"
      registry-username: ${{ github.ref_name }}@example.com
      registry-password: ${{ steps.create-customer.outputs.license-id }}
      chart: oci://registry.replicated.com/${{ inputs.app-slug }}/${{ steps.create-release.outputs.channel-slug }}/${{ inputs.helm-chart-name }}
      name: ${{ inputs.app-slug }}
      version: ${{ env.APP_VERSION }}
      namespace: 'default'
      values: ${{ inputs.helm-values }}
  - name: Deploy the app with KOTS
    if: ${{ inputs.installation-method == 'kots' }}
    uses: replicatedhq/compatibility-actions/kots-install@v0
    with:
      kubeconfig: ${{ steps.create-cluster.outputs.cluster-kubeconfig }}
      app-slug: ${{ inputs.app-slug }}/${{ steps.create-release.outputs.channel-slug }}
      license-file: ${{ steps.create-customer.outputs.license-file }}
      app-version-label: ${{ env.APP_VERSION }}
      config-values: ${{ inputs.kots-config-values }}
  - name: Run the test script
    shell: bash
    run: |
      chmod +x ${{ inputs.test-script }}
      mkdir -p ~/.kube
      echo "${{ steps.create-cluster.outputs.cluster-kubeconfig }}" > ~/.kube/config
      ./${{ inputs.test-script }}
  - name: Remove Cluster
    id: remove-cluster
    uses: replicatedhq/compatibility-actions/remove-cluster@v0
    continue-on-error: true # It could be that the cluster is already removed
    with:
      api-token: ${{ inputs.api-token }}
      cluster-id: ${{ steps.create-cluster.outputs.cluster-id }}
  - name: 'Archive Customer'
    id: 'archive-customer'
    if: always()
    uses: replicatedhq/compatibility-actions/archive-customer@v0
    with:
      api-token: ${{ inputs.api-token }}
      customer-id: ${{ steps.create-customer.outputs.customer-id }}
  - name: 'Archive Channel'
    id: 'archive-channel'
    if: always()
    uses: replicatedhq/compatibility-actions/archive-channel@v0
    with:
      app-slug: ${{ inputs.app-slug }}
      api-token: ${{ inputs.api-token }}
      channel-slug: ${{ steps.create-release.outputs.channel-slug }}
