name: "Remove cluster"
description: "Remove a cluster"
inputs:
  api-token:
    description: "API Token."
    required: true
    default: ""
  cluster-id:
    description: "Cluster id to remove."
    required: true
runs:
  using: "node20"
  main: "dist/index.js"
