name: "Archive Channel"
description: "Archive a channel"
inputs:
  api-token:
    description: "API Token."
    required: true
  app-slug:
    description: "App Slug."
    required: true
  channel-slug:
    description: "The slug of the channel to archive."
    required: true
runs:
  using: "node20"
  main: "index.js"
