name: "Expose Port"
description: "Expose Port"
inputs:
  api-token:
    description: "API Token."
    required: true
    default: ""
  cluster-id:
    description: "Cluster id to expose port for"
    required: true
    default: ""
  port:
    description: "Cluster Port to expose."
    required: true
    default: ""
  protocols:
    description: "Protocols to expose port for. Default is `https`. Possible values are `http`, `https`, `http,https`."
    required: false
    default: "https"
outputs:
  hostname: # hostname of the exposed port
    description: "Contains the hostname of the exposed port."
runs:
  using: "node16"
  main: "dist/index.js"
