name: "Create Object Store"
description: "Create Object Store"
inputs:
  api-token:
    description: "API Token."
    required: true
    default: ""
  cluster-id:
    description: "Cluster id to attach object store to"
    required: true
    default: ""
  bucket-prefix:
    description: "A prefix for the bucket name to be created."
    required: true
    default: ""
  timeout-minutes:
    description: "Time to wait for the object store to have a status of `ready`"
    required: false
    default: "20"
outputs:
  addon-id: # id of the addon
    description: "Contains the id of the addon."
  bucket-name: # final name of the bucket
    description: "Contains the final bucket name."
  bucket-prefix: # prefix of the bucket
    description: "Contains the prefix of the bucket."
  service-account-name: # name of the service account
    description: "Contains the name of the service account."
  service-account-name-read-only: # name of the read only service account
    description: "Contains the name of the read only service account."
  service-account-namespace: # namespace of the service account
    description: "Contains the namespace of the service account."
runs:
  using: "node16"
  main: "dist/index.js"
