name: "Create Object Store"
description: "Create Object Store"
inputs:
  api-token:
    description: "API Token."
    required: true
    default: ""
  cluster-name:
    description: "Name of the cluster to provision"
    required: true
    default: ""
  disk:
    description: "Disk size in GiB"
    required: false
  tags:
    description: |
      Tags to assign to the cluster.
      Example:
      <pre>tags: \|
        - key: "department"
          value: "engineering"</pre>
    required: false
outputs:
  cluster-id: # id of the cluster
    description: "Contains the cluster id."
  cluster-kubeconfig: # kubeconfig of the cluster
    description: "Contains the kubeconfig to connect with the cluster."
runs:
  using: "node16"
  main: "dist/index.js"
