name: test - create-postgres

on:
  pull_request:
    branches:
      - main
    paths:
      - create-postgres/**
      - .github/workflows/test-create-postgres.yml

concurrency:
  group: test-create-postgres-${{ github.head_ref }}
  cancel-in-progress: true

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "npm"
          cache-dependency-path: |
            **/package-lock.json

      - name: build
        run: make package-create-postgres

      - name: create-cluster
        id: create-cluster
        uses: replicatedhq/compatibility-actions/create-cluster@v1
        with:
          api-token: ${{ secrets.REPLICATED_API_TOKEN }}
          kubernetes-distribution: eks
          timeout-minutes: 5

      - name: test create-postgres
        id: create-postgres
        uses: ./create-postgres
        with:
          api-token: ${{ secrets.REPLICATED_API_TOKEN }}
          cluster-id: ${{ steps.create-cluster.outputs.cluster-id }}
          version: "16.3"
          timeout-minutes: 10

      - name: remove cluster
        if: always()
        uses: replicatedhq/compatibility-actions/remove-cluster@v1
        continue-on-error: true # It could be that the cluster is already removed
        with:
          api-token: ${{ secrets.REPLICATED_API_TOKEN }}
          cluster-id: ${{ steps.create-cluster.outputs.cluster-id }}
